version: '3'
services:
  sender:
    build:
      context: .
      dockerfile: ./Dockerfile.send
    links:
      - rabbitmq
    depends_on:
      - receiver
    environment:
      - AMPQ_ADDRESS=amqp://rabbitmq:5672
      - MTECH_MSG=hello
  receiver:
    build:
      context: .
      dockerfile: ./Dockerfile.receive
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - AMPQ_ADDRESS=amqp://rabbitmq:5672
      - PYTHONUNBUFFERED=0
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
