Vagrant.configure("2") do |config|
  config.vm.box = "fedora/28-cloud-base"
   config.vm.provision "shell", inline: <<-SHELL
     dnf install puppet -y
   SHELL
  config.vm.provision :puppet do |puppet|
      puppet.manifest_file = "hello.pp"
  end
end
